---

- name:       Update APT package cache
  sudo:       yes
  apt:        update_cache=yes

- name:       Install packages
  sudo:       yes
  apt:        pkg={{ item }} state=installed
  with_items:
    - lib32gcc1

- name:       Download SteamCMD
  get_url:
     url:  http://media.steampowered.com/installer/steamcmd_linux.tar.gz
     dest: /home/{{ user }}/steamcmd_linux.tar.gz

- file:
    path:  /home/{{ user }}/steamcmd
    state: directory

- unarchive:
     src:  /home/{{ user }}/steamcmd_linux.tar.gz
     dest: /home/{{ user }}/steamcmd/
     copy: no

- template:
    src:  update-cs-go.j2
    dest: /home/{{ user }}/steamcmd/update-cs-go

- command: ./steamcmd.sh +runscript /home/{{ user }}/steamcmd/update-cs-go
  args:
     chdir: /home/{{ user }}/steamcmd/
